address: localhost
port: 3000
timeout: 30
pid: /tmp/web_server.pid
socket: /tmp/web_server.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
daemonize: true
chdir: $STACK_PATH
environment: $RAILS_ENV
log: $STACK_PATH/log/thin.log
