data_dir: /shared/import/data

# mbox files
split_regex: "^From .+@.+"
#split_regex: "^From .+@example.com.+"

# individual emails
#split_regex: ""

# Listserv files
#split_regex: "^========================================================================="

default_trust_level: 1
prefer_html: true
staged: true
index_only: false

group_messages_by_subject: false
