discourse_sample_plugin:
  discourse_sample_plugin_enabled: true
site_settings:
  plugin_setting:
    default: "some value"
  test_some_topic_id:
    default: 0
  test_some_other_topic_id:
    default: 0
  enable_experimental_sample_plugin_feature:
    default: false
    client: true
    hidden: true
    upcoming_change:
      impact: "feature,admins"
      status: "alpha"
  test_objects_with_uploads:
    type: objects
    default: "[]"
    schema:
      name: "test_object"
      properties:
        name:
          type: string
        upload_id:
          type: upload
