defaults: &defaults
  uri: <%= uri = URI.parse(ENV['REDIS_URL'] || ENV['OPENREDIS_URL'] || ENV['REDISCLOUD_URL'] || ENV['REDISGREEN_URL'] || ENV['REDISTOGO_URL'] || "redis://localhost:6379") %>
  host: <%= uri.host %>
  port: <%= uri.port %>
  password: <%= uri.password %>
  db: 0
  cache_db: 2

development:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults
  db: 0
  cache_db: 0

production:
  <<: *defaults
