---
chdir: /home/hackinmad/discourse/current
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: /home/hackinmad/discourse/shared/log/thin.log
pid: /home/hackinmad/discourse/shared/pids/thin.pid
socket: /home/hackinmad/discourse/shared/sockets/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 4
daemonize: true
onebyone: true
