name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    container: discourse/discourse_test:release
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        target: [core, plugins]
        os: [ubuntu-latest]
        ruby: ["2.7"]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gem-

      - name: Setup gems
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os }}-yarn-

      - name: Yarn install
        run: yarn install

      - name: Checkout official plugins
        if: matrix.target == 'plugins'
        run: bin/rake plugin:install_all_official

      - name: Rubocop (core and core plugins)
        if: matrix.target == 'core'
        run: bundle exec rubocop .

      - name: Rubocop (all plugins)
        if: matrix.target == 'plugins'
        run: bundle exec rubocop plugins

      - name: ESLint (core)
        if: matrix.target == 'core'
        run: yarn eslint --ext .js,.js.es6 --no-error-on-unmatched-pattern app/assets/javascripts

      - name: ESLint (core plugins)
        if: matrix.target == 'core'
        run: yarn eslint --ext .js,.js.es6 --no-error-on-unmatched-pattern plugins/**/{test,assets}/javascripts

      - name: ESLint (all plugins)
        if: matrix.target == 'plugins'
        run: yarn eslint --ext .js,.js.es6 --no-error-on-unmatched-pattern plugins/**/{test,assets}/javascripts

      - name: Prettier (core and core plugins)
        if: matrix.target == 'core'
        run: |
          yarn prettier -v
          yarn prettier --list-different \
            "app/assets/stylesheets/**/*.scss" \
            "app/assets/javascripts/**/*.{js,es6}" \
            "plugins/**/assets/stylesheets/**/*.scss" \
            "plugins/**/assets/javascripts/**/*.{js,es6}"

      - name: Prettier (all plugins)
        if: matrix.target == 'plugins'
        run: |
          yarn prettier -v
          yarn prettier --list-different \
            "plugins/**/assets/stylesheets/**/*.scss" \
            "plugins/**/assets/javascripts/**/*.{js,es6}"

      - name: Ember template lint (core and core plugins)
        if: matrix.target == 'core'
        run: |
          yarn ember-template-lint \
            app/assets/javascripts \
            plugins/**/assets/javascripts

      - name: Ember template lint (all plugins)
        if: matrix.target == 'plugins'
        run: |
          yarn ember-template-lint \
            plugins/**/assets/javascripts

      - name: Core English locale
        if: matrix.target == 'core'
        run: bundle exec ruby script/i18n_lint.rb "config/**/locales/{client,server}.en.yml"

      - name: Plugin English locale
        if: matrix.target == 'plugins'
        run: bundle exec ruby script/i18n_lint.rb "plugins/**/locales/{client,server}.en.yml"
